### ISSUE TITLE
multi gpu training

### ISSUE THREAD

**Issue by ksh11023** [ZM-Zhou/SDFA-Net_pytorch#1]
Hello,

Thank you for the nice Work!

Can this code be trained with multi gpus?  'CUDA_VISIBLE_DEVICES=0,1,2,3 python train_dist.py dosen't work..

Thankyou.

**Comment by ksh11023** [comment]
Hello, 
Thank you for the swift reply!

I have tried the way you have mentioned, However I got this error.

![1](https://user-images.githubusercontent.com/50094436/194234091-d736268f-5e69-45d5-98a8-cfcedd6fc7ac.png)

I am running my code on  RTX 3090 CUDA 11.2, pyorch  1.9.0.
Can you please give me some advices? 

Thank you.

**Comment by ZM-Zhou** [comment]
From the error message, it seems that the arguments of NCCL are invalid. You may check that `torch` could recognize all GPUs (I guess this is the main problem because of the message `.. NCCL INFO NET/IB No device found.`) and the port:12345 is free. This repo worked well on V100, CUDA 10.2, and Pytoch 1.7.0,  but I'm not sure if the code supports parallel training on a higher version.
I hope the above information can help you.
