### ISSUE TITLE
image cropping

### ISSUE THREAD

**Issue by ksh11023** [ZM-Zhou/SDFA-Net_pytorch#10]
Hello,

Does cropping the image to (192x640) produces better result compared to directly using (384x1280) for training? 

Thank you.

**Comment by ZM-Zhou** [comment]
Hi ksh11023,
There are two main advantages of using image cropping in my opinion: 1. saving the GPU memory; 2. the discrete depth prediction could benefit from the random resizing and croping augmentations (mentiond in FAL-Net).
I didn't try to use the raw high-resolution image for training due to GPU limitations, so I'm not sure which strategy is better.

**Comment by ksh11023** [comment]
Thank you for the reply!
